---
- hosts: all
  become: true
  vars_files:
    - vars.yml
  roles:
    - hostname
    - webserver
    - mailserver
    - database

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: set fqdn
      hostname:
        name: "{{ hostname }}"
