- name: Ldap | install all ldap related packages
  apt: pkg={{ item }} state=present
  with_items:
    - postfix-ldap
    - dovecot-ldap
    - ldap-utils
    - libnet-ldap-perl
    - postfix-ldap
    - phpldapadmin
