- name: Mailserver | install all mailserver packages
  apt: pkg={{ item }} state=present
  with_items:
    - postfix
    - postfix-ldap
    - postfix-pcre
    - postgrey
    - amavisd-new
    - clamav
    - clamdscan
    - sasl2-bin
    - libsasl2-2
    - php-auth-sasl
    - dovecot-core
    - dovecot-imapd
    - dovecot-ldap
    - dovecot-lmtpd
    - dovecot-managesieved
    - dovecot-mysql
    - dovecot-pop3d
    - dovecot-sieve
    - opendkim
    - opendkim-tools
    - libopendkim10
    - spamassassin

- import_tasks: opendkim.yml
- import_tasks: amavis.yml
- import_tasks: dovecot.yml
- import_tasks: postfix.yml
