- name: roundcube language
  debconf:
    name: roundcube-core
    question: roundcube/language
    value: "en_US"
    vtype: select

- name: roundcube database-type
  debconf:
    name: roundcube-core
    question: roundcube/database-type
    value: "mysql"
    vtype: select

- name: roundcube mysql admin pass
  debconf:
    name: roundcube-core
    question: roundcube/mysql/admin-pass
    value: "{{ db.password }}"
    vtype: password

- name: roundcube app-user
  debconf:
    name: roundcube-core
    question: roundcube/db/app-user
    value: "{{ db.user }}"
    vtype: string

- name: roundcube dbconfig
  debconf:
    name: roundcube-core
    question: roundcube/dbconfig-install
    value: "true"
    vtype: boolean

- name: roundcube dbconfig-reinstall
  debconf:
    name: roundcube-core
    question: roundcube/dbconfig-reinstall
    value: "true"
    vtype: boolean

- name: roundcube mysql user
  debconf:
    name: roundcube-core
    question: roundcube/mysql/admin-user
    value: "{{ db.user }}"
    vtype: string

- name: roundcube restart webserver
  debconf:
    name: roundcube-core
    question: roundcube/restart-webserver
    value: "true"
    vtype: boolean

- name: roundcube dbname
  debconf:
    name: roundcube-core
    question: roundcube/db/dbname
    value: "roundcube"
    vtype: string

- name: roundcube imap host
  debconf:
    name: roundcube-core
    question: roundcube/hosts
    value: "localhost:143"
    vtype: string

- name: roundcube host
  debconf:
    name: roundcube-core
    question: roundcube/remote/host
    value: "localhost"
    vtype: string

- name: roundcube mysql connection method
  debconf:
    name: roundcube-core
    question: roundcube/mysql/method
    value: "TCP/IP"
    vtype: select

- name: roundcube mysql port
  debconf:
    name: roundcube-core
    question: roundcube/remote/port
    value: "3306"
    vtype: string

- name: roundcube reconfigure webserver
  debconf:
    name: roundcube-core
    question: roundcube/reconfigure-webserver
    value: "apache2"
    vtype: multiselect

- name: roundcube dbconfig-upgrade
  debconf:
    name: roundcube-core
    question: roundcube/dbconfig-upgrade
    value: "true"
    vtype: boolean

- name: roundcube upgrade backup
  debconf:
    name: roundcube-core
    question: roundcube/upgrade-backup
    value: "true"
    vtype: boolean

- name: Webmail & Ldap admin | install webmail client packages
  apt: pkg={{ item }} state=present
  with_items:
    - php-ldap
    - php-net-ldap
    - php-net-ldap2
    - php-net-ldap3
    - php5.6-ldap
    - roundcube
    - roundcube-core
    - roundcube-mysql
    - roundcube-plugins
    - roundcube-plugins-extra
    - dbconfig-common
    - dbconfig-mysql

- name: Add roundcube dbconfig file
  template:
    src: templates/roundcube.conf.j2
    dest: "/etc/dbconfig-common/roundcube.conf"

- name: Add roundcube apache conf
  file:
    src=/etc/apache2/conf-available/roundcube.conf
    dest=/etc/apache2/conf-enabled/roundcube.conf
    state=link

- name: Enable roundcube alias
  lineinfile:
    dest: /etc/apache2/conf-enabled/roundcube.conf
    regexp: '#    Alias /roundcube /var/lib/roundcube'
    line: 'Alias /roundcube /var/lib/roundcube'
    state: present

- name: Add roundcube config.inc.php
  template:
    src: templates/config.inc.php.j2
    dest: "/etc/roundcube/config.inc.php"
