- name: Webmail & Ldap admin | install webmail client packages
  apt: pkg={{ item }} state=present
  with_items:
    - phpldapadmin
    - php-ldap
    - php-net-ldap
    - php-net-ldap2
    - php-net-ldap3
    - php5.6-ldap
    - roundcube
    - roundcube-core
    - roundcube-mysql
    - roundcube-plugins
    - roundcube-plugins-extra
