- name: Webmail & Ldap admin | install webmail client packages
  apt: pkg={{ item }} state=present
  with_items:
    - phpldapadmin
    - php-ldap
    - php-net-ldap
    - php-net-ldap2
    - php-net-ldap3
    - php5.6-ldap
    - roundcube
    - roundcube-core
    - roundcube-mysql
    - roundcube-plugins
    - roundcube-plugins-extra

- name: Add roundcube conf
  file:
    src=/etc/apache2/conf-available/roundcube.conf
    dest=/etc/apache2/conf-enabled/roundcube.conf
    state=link

- name: Enable roundcube alias
  lineinfile:
    dest: /etc/apache2/conf-enabled/roundcube.conf
    regexp: '#    Alias /roundcube /var/lib/roundcube'
    line: 'Alias /roundcube /var/lib/roundcube'
    state: present
